#!/bin/sh

# Source and export D-Bus session info
. /tmp/dbus-info
export DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_PID
export DBUS_SESSION_BUS_WINDOWID

/usr/lib/libresourceqt-tests/test-resource-engine "$@"
