#!/bin/sh
##############################################################################
#  This file is part of libresourceqt                                        #
#                                                                            #
#  Copyright (C) 2010 Nokia Corporation.                                     #
#                                                                            #
#  This library is free software; you can redistribute                       #
#  it and/or modify it under the terms of the GNU Lesser General Public      #
#  License as published by the Free Software Foundation                      #
#  version 2.1 of the License.                                               #
#                                                                            #
#  This library is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU          #
#  Lesser General Public License for more details.                           #
#                                                                            #
#  You should have received a copy of the GNU Lesser General Public          #
#  License along with this library; if not, write to the Free Software       #
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  #
#  USA.                                                                      #
##############################################################################

# Source and export D-Bus session info

if test -e /tmp/session_bus_address.user; then
    . /tmp/session_bus_address.user
else
    . /tmp/dbus-info || . /tmp/dbus-info-address
    export DBUS_SESSION_BUS_ADDRESS
    export DBUS_SESSION_BUS_PID
    export DBUS_SESSION_BUS_WINDOWID
fi

/usr/lib/libresourceqt-tests/test-resource-engine "$@"
